# https://taskfile.dev

version: '3'

env:
  DOCKER_PHP_SERVICE: composer

includes:
  docker:
    taskfile: .docker/php/DockerTasks.yml
    dir: .docker/php

tasks:
  install:
    desc: Install Sylius
    cmds:
      - docker-compose --profile=$DOCKER_PHP_SERVICE up -d
      - docker-compose exec --user=33:33 $DOCKER_PHP_SERVICE php bin/console sylius:install --no-interaction -vvv
      - task: fixtures
      - docker-compose exec --user=33:33 $DOCKER_PHP_SERVICE php bin/console sylius:install:assets -vvv
      - docker-compose exec --user=33:33 $DOCKER_PHP_SERVICE php bin/console sylius:theme:assets:install public --no-interaction
      - docker-compose exec $DOCKER_PHP_SERVICE php bin/console lexik:jwt:generate-keypair --skip-if-exists --no-interaction
  fixtures:
    desc: Install Sylius Fixtures
    cmds:
      - docker-compose exec --user=33:33 $DOCKER_PHP_SERVICE php bin/console sylius:fixtures:load default --no-interaction  -vvv
  clean:
    cmds:
      - docker-compose --profile=$DOCKER_PHP_SERVICE down -v
  db-clean:
    cmds:
      - docker-compose exec $DOCKER_PHP_SERVICE php bin/console doctrine:database:drop --if-exists --force
      - docker-compose exec $DOCKER_PHP_SERVICE php bin/console doctrine:database:create
      - docker-compose exec $DOCKER_PHP_SERVICE php bin/console doctrine:migrations:migrate --no-interaction
      - docker-compose exec $DOCKER_PHP_SERVICE php bin/console doctrine:schema:validate
  build:
    dir: .docker/php
    cmds:
      - docker build --target php-distroless --progress plain -t piotrkardasz/sylius-distroless-2023:php-distroless .
      - docker build --target php-debian --progress plain -t piotrkardasz/sylius-distroless-2023:php-debian .
      - docker build --target php-sury-debian --progress plain -t piotrkardasz/sylius-distroless-2023:php-sury-debian .
      - docker build --target php-sury-ubuntu --progress plain -t piotrkardasz/sylius-distroless-2023:php-sury-ubuntu .
      - docker build --target php-alpine --progress plain -t piotrkardasz/sylius-distroless-2023:php-alpine .
      - docker build --target php-sury-debian-no-gd --progress plain -t piotrkardasz/sylius-distroless-2023:php-sury-debian-no-gd .
  publish:
    dir: .docker/php
    cmds:
      - docker push piotrkardasz/sylius-distroless-2023:php-distroless
      - docker push piotrkardasz/sylius-distroless-2023:php-debian
      - docker push piotrkardasz/sylius-distroless-2023:php-sury-debian
      - docker push piotrkardasz/sylius-distroless-2023:php-sury-ubuntu
      - docker push piotrkardasz/sylius-distroless-2023:php-alpine
      - docker push piotrkardasz/sylius-distroless-2023:php-sury-debian-no-gd
